# Workaround for the fact that GitHub actions will stop running if a project
# doesn't have recent commits
name: Make commit to default branch
on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  checkpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp
        run: |
          echo CHECKPOINT="$(date +%s)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Create checkpoint file
        run: echo $CHECKPOINT > last-change.checkpoint
      - name: Commit checkpoint
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'sophie.a.debs@gmail.com'
          git add .
          git commit -m "Checkpoint at $CHECKPOINT"
          git push
